import { CaseStudy, FAQItem, SystemCard, MetricItem, IntegrationTool } from './types';

export const CASE_STUDIES: CaseStudy[] = [
  {
    id: 'derby-men',
    badge: 'Clothing Brand',
    title: 'Derby Men',
    client: 'Derby Men',
    role: 'Clothing Brand',
    quote: "Honestly, customer follow-up was one of those things we'd always get to eventually, but not always on time. Now it's handled consistently and I barely have to think about it.",
    accent: 'rose',
    phase: '15+ Hours Weekly',
    surface: 'More Consistent Execution',
    ownership: 'Built Inside Your Business',
  },
  {
    id: 'ayaani-diamonds',
    badge: 'Jewelry Brand',
    title: 'Ayaani Diamonds',
    client: 'Ayaani Diamonds',
    role: 'Jewelry Brand',
    quote: "We weren't losing customers because of the product. Most of the time it was just slow replies. Fixing that made a bigger difference than I expected.",
    accent: 'emerald',
    phase: '15+ Hours Weekly',
    surface: 'More Consistent Execution',
    ownership: 'Built Inside Your Business',
  },
  {
    id: 'espanshe',
    badge: 'Fashion Brand',
    title: 'Espanshe',
    client: 'Espanshe',
    role: 'Fashion Brand',
    quote: "We had a decent list of past customers sitting there and, if I'm honest, we weren't doing much with it. Now people come back regularly without us chasing it.",
    accent: 'indigo',
    phase: '15+ Hours Weekly',
    surface: 'More Consistent Execution',
    ownership: 'Built Inside Your Business',
  },
  {
    id: 'glamzy-beauty',
    badge: 'Cosmetic Brand',
    title: 'Glamzy Beauty',
    client: 'Glamzy Beauty',
    role: 'Cosmetic Brand',
    quote: "The number of 'Where's my order?' messages dropped a lot. Customers seem more informed and the team isn't spending half the day answering the same questions.",
    accent: 'amber',
    phase: '15+ Hours Weekly',
    surface: 'More Consistent Execution',
    ownership: 'Built Inside Your Business',
  },
  {
    id: 'protein-nation',
    badge: 'Supplements Brand',
    title: 'Protein Nation',
    client: 'Protein Nation',
    role: 'Supplements Brand',
    quote: "The funny thing is I stopped checking whether follow-ups were happening. A few months ago I would've worried about it. Now it just gets done.",
    accent: 'pink',
    phase: '15+ Hours Weekly',
    surface: 'More Consistent Execution',
    ownership: 'Built Inside Your Business',
  },
  {
    id: 'urban-outfitters',
    badge: 'Clothing Brand',
    title: 'Urban Outfitters',
    client: 'Urban Outfitters',
    role: 'Clothing Brand',
    quote: "We had plenty of past customers but no real process for reaching them again. It was mostly manual. Now it's structured and actually consistent.",
    accent: 'sky',
    phase: '15+ Hours Weekly',
    surface: 'More Consistent Execution',
    ownership: 'Built Inside Your Business',
  },
  {
    id: 'atlas-supply',
    badge: 'Consumer Products Brand',
    title: 'Atlas Supply Co.',
    client: 'Atlas Supply Co.',
    role: 'Consumer Products Brand',
    quote: "If I'm honest, the biggest benefit wasn't growth. It was getting my time back. I stopped being the person everyone needed for every decision and the business ran smoother because of it.",
    accent: 'violet',
    phase: '15+ Hours Weekly',
    surface: 'More Consistent Execution',
    ownership: 'Built Inside Your Business',
  }
];

export const FAQ_ITEMS: FAQItem[] = [
  {
    id: 'faq-1',
    question: 'What does an engagement look like?',
    answer: 'Engagements are structured into two distinct phases. Phase 1 is a 3-month strategic Consult, where we audit your stack, map workflows, configure local tools, and design your System Blueprint. Phase 2 is a 4-6 week custom Build, where we write production-grade code directly in your repositories and hand you complete ownership.',
  },
  {
    id: 'faq-2',
    question: 'How do you figure out what to build?',
    answer: 'During the Consult, our team performs a hands-on audit of your current applications, data storage, team workflows, and customer paths. We locate high-leverage friction points (e.g., redundant text processing, slow customer reply times, or data siloed split across CRMs) and map agentic workflows that compound value.',
  },
  {
    id: 'faq-3',
    question: 'Who actually builds it?',
    answer: 'We architect everything in-house with senior AI Systems Architects and staff engineers. For specialized custom tasks, we source, qualify, and manage highly integrated developers directly under our supervision. You work with a dedicated lead architect (such as Davis) from start to finish.',
  },
  {
    id: 'faq-4',
    question: 'What if we need something custom?',
    answer: 'Everything we ship is customized. We do not sell boxed software or force you into a proprietary API platform. Whether you need custom local routing rules, fine-tuned open-source clinical voice agents, or complex multi-LLM workflows with hybrid embeddings, we build it explicitly to match your criteria.',
  },
];

export const METRICS: MetricItem[] = [
  {
    id: 'metric-1',
    value: '99.9',
    suffix: '%',
    label: 'System Uptime',
    description: 'Production-grade reliability across every custom agent deployment we ship.',
    accentColor: 'red',
  },
  {
    id: 'metric-2',
    value: '100',
    suffix: '%',
    label: 'Client-Owned',
    description: 'Every line of code, container repository, and database secret belongs completely to you.',
    accentColor: 'blue',
  },
  {
    id: 'metric-3',
    value: '2',
    suffix: ' phases',
    label: 'One Engagement',
    description: 'Consult, then build. One continuous process, not two disjointed transactions.',
    accentColor: 'red',
  },
  {
    id: 'metric-4',
    value: '0',
    suffix: ' migrations',
    label: 'Built In Your Environment',
    description: 'We code directly in your cloud accounts and GitHub repos from day one. Nothing to migrate.',
    accentColor: 'blue',
  },
  {
    id: 'metric-5',
    value: '1',
    suffix: ' team, sourced',
    label: 'Right Team Per Project',
    description: 'Engineers, developers, and integration experts carefully selected to match your stack.',
    accentColor: 'blue',
  },
  {
    id: 'metric-6',
    value: '90',
    suffix: ' day',
    label: 'Post-Launch Support',
    description: 'A generous active support and optimization window after every system goes live.',
    accentColor: 'red',
  }
];

export const INTEGRATION_TOOLS: IntegrationTool[] = [
  { id: 'slack', name: 'Slack', logoType: 'MessageSquareIcon', color: 'text-amber-500' },
  { id: 'gdrive', name: 'Google Drive', logoType: 'FolderIcon', color: 'text-blue-500' },
  { id: 'salesforce', name: 'Salesforce', logoType: 'CloudLightningIcon', color: 'text-sky-500' },
  { id: 'zoom', name: 'Zoom', logoType: 'VideoIcon', color: 'text-blue-400' },
  { id: 'notion', name: 'Notion', logoType: 'FileTextIcon', color: 'text-slate-400' },
  { id: 'gmail', name: 'Gmail', logoType: 'MailIcon', color: 'text-rose-500' },
  { id: 'gcal', name: 'Google Calendar', logoType: 'CalendarIcon', color: 'text-emerald-500' },
  { id: 'github', name: 'GitHub', logoType: 'GithubIcon', color: 'text-indigo-400' },
  { id: 'telegram', name: 'Telegram', logoType: 'SendIcon', color: 'text-sky-500' },
  { id: 'mailchimp', name: 'Mailchimp', logoType: 'MailIcon', color: 'text-yellow-500' },
  { id: 'hubspot', name: 'Hubspot', logoType: 'FlameIcon', color: 'text-orange-500' },
  { id: 'monday', name: 'Monday.com', logoType: 'SlidersIcon', color: 'text-indigo-500' }
];
